# Run from DC

cls
$Computerlist = "AMRNMCVSDS01","AMRNDSVRDB01","AMRNDSVDAP02","AMRNDSVPJB01","AMRNDSVPSW03","AMRNDSVPWI05","AMRNMCVPAP32","AMRNMCVPWI02","AMRNMCVDAP30","AMRNMCVPAP36","AMRNDSVPNP02","AMRNMCVPAP31","AMRNMCVDWI01","AMRNMCVPWI01","AMRNDSVPAP57","AMRNDSVDDB08","AMRNDSVPCTX89","AMRNDSVPAD02","AMRNDSVPJB02","AMRNDSVPLD01","AMRNDSVPMV02","AMRNDSVPSW02","AMRNDSVPDB18","AMRNDSVSAP03","AMRNDSVSAP04","AMRNDSVDAP06","AMRNDSVSDB03","AMRNDSVDCS01","AMRNDSVPAP13","AMRNMCVPDB07","AMRNDSVPAP53","AMRNDSVPAX13","AMRNDSVPAP59","AMRNDSVPAP32","AMRNMCVDAP14","AMRNDSVPCX03","AMRNDSVPDB20","AMRNDSVPAP25","AMRNDSVPCX01","AMRNDSVPAD01","AMRNDSVDAP03","AMRNDSVPAP08","AMRNDSVPAP04","AMRNDSVDWI02","AMRNDSVPAX11","AMRNDSVPAP21","AMRNDSVPAP24","AMRNDSVPAP58","AMRNDSVPCX00","AMRNDSVPAP30","AMRNMCVPAP02","STLUSNDSVPTS01","AMRNMCVDDB10","AMRNDSVPCTX20","AMRNDSVPDB61","AMRNDSVPAD04","AMRNDSVPCS02","AMRNDSVPAP12","AMRNDSVPAP06","AMRNDSVPAP16","AMRNDSVPAP18","AMRNDSVPAP63","AMRNDSVPAP61","REY2MXNDSPPAP01","AMRNDSVPWI03","AMRNDSVPAP54","AMRNDSVPDC01NEW","AMRNDSVPDB02","AMRNDSVPCX22","AMRNDSVPCX23","AMRNDSVPDB01","AMRNDSVDAP13","AMRNDSVDAP17","AMRNDSVDAP25","AMRNDSVPAP55","AMRNDSVSAX11","AMRNDSVPCX04","AMRNDSVPDH01","amrnmcvpcl01","AMRNMCVPAP35","AMRNMCVPAP41","AMRNDSVPDH03","AMRNMCVPDB09","AMRNMCVDDB08","AMRNMCVDDB02","AMRNMCVDAP15","AMRNMCVPDB14","AMRNMCVPDH02","AMRNDSVPAP03","AMRNMCVPDB08","AMRNDSVDAP36","AMRNDSVTAP25","AMRNDSVSAX12","FWUSNDSPPHV01","AMRNDSVPAP51","AMRNDSVPPA01","FWUSNDSPPMAIN","AMRNMCVPDB10","AMRNDSVPDB05","AMRNMCVPAP39","AMRNDSVPDB11","AMRNMCVPDB06","AMRNDSVPDB62","AMRNDSVPDB10","AMRNDSVPDB03","AMRNDSVDAP16","AMRNDSVPCX98","AMRNDSVDAP18","AMRNDSVPCX61","AMRNDSVPDB16","AMRNDSVSMV02","AMRNDSVSCS02","AMRNDSVSAP03","AMRNDSVDDB18","AMRNDSVDWI03","AMRNDSVPDB13","AMRNMCVPDB04","AMRNDSVDAP07","FWUSNDSVPPDM","AMRNDSVPCX09","AMRNDSVPCX02","AMRNDSVDDB05","AMRNDSVDDB06","AMRNDSVPCX08","AMRNDSVPCX60","AMRNDSVPCX06","AMRNDSVPCX07","AMRNDSVDDB01","AMRNDSVPCX05","AMRNDSVDAX01","AMRNMCVPAP37","AMRNDSVPSW01"
# Start-Transcript -Path C:\temp\dnsupdate.txt -Append

foreach ($computername in $computerlist) { 
        Write-Host "Checking $computername"
  if (test-Connection -ComputerName $computername -Count 1 -Quiet ) {  
          # Get Nic Settings
            $nic = Get-NetIPConfiguration -CimSession $computername 
            $index = $nic.InterfaceIndex
            $Current_dnsserver = $nic.DNSServer |?{$_.ServerAddresses -ge 1} | select -ExpandProperty ServerAddresses
          # Check DNS Settings
            $NewDns = "10.112.10.107","10.138.3.7"
            $compared = Compare-Object  -ReferenceObject $NewDns -DifferenceObject  $Current_dnsserver 

            if ($compared -ne $null ){write-host "do stuff"

                Write-Host "`nUPDATING - $computername current dns: $Current_dnsserver`n"
                Set-DnsClientServerAddress -InterfaceIndex $index -ServerAddresses ("10.112.10.90","10.138.3.7") -CimSession $computername
                

            }else{
             Write-Host "`tSKIPPING - $computername dns: $Current_dnsserver "
            }
         } 
      }   
        #Stop-Transcript
    